### ISSUE TITLE
The program not working, nothing appeared

### ISSUE THREAD

**Issue by thq642** [AndyFilter/QuizizzSupport#11]
after i click the .exe program,  and nothing appeared

**Comment by ghost** [comment]
You'll have to wait, It takes a while to startup.

**Comment by thq642** [comment]
but when I saw in the task manager the process disappeared and idk why

**Comment by AndyFilter** [comment]
Well I dont really have a way to replicate your issue, but you can try to fix this issue by downloading [**.NET 5**](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.3-windows-x64-installer) and [**.NET CORE 3.1**](https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.12-windows-x64-installer)

**Comment by thq642** [comment]
still doesn't work :(
