### ISSUE TITLE
Live quiz ID

### ISSUE THREAD

**Issue by HerrInspektor** [AndyFilter/QuizizzSupport#14]
Hello there! Is there a way to get the Quiz Id for a Live quiz?

**Comment by AndyFilter** [comment]
I assume you are referring to QuizId and not the Quiz Code, So there are multiple of ways to get it. For example doing a simple /CheckRoom Post Request leaves you a LongQuizId which might be used for something, I dont know. At this point you need to put something from your self. 😇

**Comment by HerrInspektor** [comment]
Yes I needed the QuizId. Thank you for your tip, will play around with it. 😃
