### ISSUE TITLE
Wont give answers

### ISSUE THREAD

**Issue by ClexFN** [AndyFilter/QuizizzSupport#19]
Everytime I enter the code into the quizziz support framework it keeps saying "complete actions first" what does that mean?

**Comment by AndyFilter** [comment]
There should appear a **popup** window on your screen, and on it you have a choice between logging into Quizziz to get your answers or opening a website (in a browser where you are already logged in). If you choose the latter you'll have to follow the instructions stated in the program which is just copying the text into the textbox below. Though please keep in mind that **the program is no longer supported** and the last update was over 2 years ago. Quizziz probably changed a lot of things about their API and in consequence my program will not function correctly. 👍🏼
