### ISSUE TITLE
Error(force close)

### ISSUE THREAD

**Issue by XrEl1** [AndyFilter/QuizizzSupport#2]
hey,thanks for making this but when i started the program and put the right quiziz code i press get answer but its closing

**Comment by AndyFilter** [comment]
I assume you really put the right url/code (ex. 123456, https://quizizz.com/join?gc=123456).
And not something like: https://quizizz.com/admin/quiz/601844f3a0aa123432423/startV4

Lately I have been seeing some quizzes using a 7-8 digits codes, and these codes don't work for some reason If that's the case at the end of the week I'll have some time and maybe I'll fix it (if it's even possible)
