### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by ghost** [AndyFilter/QuizizzSupport#3]
Hi, so when I try to insert the URL (https://quizizz.com/join?gc=1234567) and click get answers it hangs for a bit then crashes. Maybe its because this is a 7-digit code instead of a 6-digit code. Let me know!

**Comment by AndyFilter** [comment]
Should be fixed in the [latest update](https://github.com/AndyFilter/QuizizzSupport/releases/tag/3.1). check it out and let me know if the issue still persists.

**Comment by ghost** [comment]
I'm sorry to tell you that, but the update isn't, unfortunately, resolving this issue. Now it says "Please wait..." and crashes. I've tested it on the .exe and the .rar

**Comment by AndyFilter** [comment]
Can you send me the link to this specific quiz that is not working?

**Comment by ghost** [comment]
Yes, of course! https://quizizz.com/join?gc=7987523 (I'm going to sleep now)

**Comment by AndyFilter** [comment]
Ok, thanks for the input the issue has been fixed and the program should not crash in case of error like this. I have updated the latest release.
