### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by idunnoooooo** [AndyFilter/QuizizzSupport#5]
Can u update the source code to 4.1? Thanks

**Comment by AndyFilter** [comment]
I do not want to update the code for 2 reasons:
- It's absolutely awful
- I'm pretty sure someone from quizizz checks GitHub for the _hacks_ once or twice a day, and that would make their lives a lot easier.

**Comment by AndyFilter** [comment]
The code has been updated to the latest version of the binaries so enjoy!
