### ISSUE TITLE
Trojan Virus?

### ISSUE THREAD

**Issue by 11H8** [AndyFilter/QuizizzSupport#6]
I'm getting a virus when I try to download this.

**Comment by AndyFilter** [comment]
No, It's just an alert from Windows when you try to open a program from unknown source, to avoid that just enable developer mode is settings ***(Windows Settings -> Update and Security -> For Developers -> Developer Mode)***.  Alternatively you can just press more info and ***Allow anyway***. Or compile source code on your own computer.
