### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by MrBoombastic** [AndyFilter/QuizizzSupport#7]
This app was working like 2-3 days ago, but now every time when I enter code, app says that is not valid. Could you fix that? I have tricky test on Friday. Thanks. :D 
![obraz](https://user-images.githubusercontent.com/18630357/107523957-8fc16180-6bb5-11eb-9a8d-c19eb3fdcc33.png)

**Comment by AndyFilter** [comment]
I'm sorry, but I could not replicate your problem. Everything works fine for me with either a code or url (the one with _/join?gc=_). Could you please contact me on Discord: IsPossible#8212. So I can get more information about this issue.

**Comment by MrBoombastic** [comment]
Suddenly it is working now. Thanks.
