### ISSUE TITLE
program does not work on live games

### ISSUE THREAD

**Issue by luqman21** [AndyFilter/QuizizzSupport#8]
when i use it on live games it does not work and says "quiz not found".
is this a bug?
however when i use it on normal games it works fine.
can you make them work on live games as those are most important

**Comment by ghost** [comment]
Make sure you're using **4.4**! Maybe reinstall? (And I've tried it myself on an exam today and it works fine!)

**Comment by AndyFilter** [comment]
As I said in earlier issues, It won't work with private quizzes. but it works for most if not every public the mode doesn't matter.

**Comment by luqman21** [comment]
Oh my one was private so will you find a way to get past this as all my
quizzes are private

**Comment by AndyFilter** [comment]
I don't think I'll ever find a way to get answers from private quizz, mainly because of the legality of this action. But perhaps someday.
